In [78]:
from numpy import random as ran
print("You can enter between 1-10, for quit enter 404")
try_again = 0
random_num = ran.randint(1,11)
print(f"Hint:{random_num}")
user_num = int(input("Enter your Guess number: "))
print(f"You enter: ({user_num})")
score = 0
boolean = True
while boolean:
    if (user_num == random_num):
        score += 1
        print(f"Correct guess! Score: {score}")
        random_num = ran.randint(1,11)
        try_again = 0
    elif(user_num == 404):
        print(f"You quitted! Your total score: {score}")
        break

    elif(try_again < 1):
        # print(f"Hint: Number is between {random_num-3} to {random_num+2}")
        if (user_num < random_num):
            print("Try again once. Hint: Enter larger number.")
        else:
            print("Try again once. Hint: Enter smaller number.")
        try_again += 1
    
    else:
        print(f"Wrong guess! Your total score: {score}")
        break
    
    # print(random_num)
    print("------------------------------")
    if(score < 2):
        print(f"Hint: {random_num}")
    user_num = int(input("Enter your Guess number: "))
    print(f"You enter: ({user_num})")

You can enter between 1-10, for quit enter 404
Hint:2
You enter: (404)
You quitted! Your total score: 0


In [79]:
import numpy as np
arr = np.array([
    [4,8,5],
    [2,7,1],
    [5,9,2]
])
# arr = np.array([
#     [7,3],
#     [2,5]
# ])
arr_transpose = arr.T
print("\nTranspose of matrix")
print(arr_transpose)
print("\nDeterminant of matrix")
print(np.linalg.det(arr))
print("\nAdjoint of matrix")
print((np.linalg.det(arr))*(np.linalg.inv(arr)))
print("\nInverse of matrix")
print(np.linalg.inv(arr))
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
print("\nA.B of matrix")
print(np.dot(A,B))





Transpose of matrix
[[4 2 5]
 [8 7 9]
 [5 1 2]]

Determinant of matrix
-57.00000000000001

Adjoint of matrix
[[  5.  29. -27.]
 [  1. -17.   6.]
 [-17.   4.  12.]]

Inverse of matrix
[[-0.0877193  -0.50877193  0.47368421]
 [-0.01754386  0.29824561 -0.10526316]
 [ 0.29824561 -0.07017544 -0.21052632]]

A.B of matrix
[[19 22]
 [43 50]]


In [80]:
import numpy as np
# x + y + z =6
# y + 3z = 11
# x – 2y + z = 0

# x = 1, y = 2, z = 3

A = np.array([
    [1,1,1],
    [0,1,3],
    [1,-2,1]
])
B = np.array([
    [6],
    [11],
    [0]
    ])
X = ((np.linalg.solve(A,B)))
print(X)

[[1.]
 [2.]
 [3.]]


In [85]:
from numpy import random as ran
import numpy
random_num = ran.randint(2,100,15)
print("Full list", random_num)
ls_prime = []
ls_notprime = []
for num in random_num:
    check_prime = True
    if(num == 2):
        check_prime = True
    for i in range(2, num):
        if(num % i == 0):
            check_prime = False

            break
    if(check_prime == True):
        ls_prime.append(num)

print(ls_prime)

Full list [51 23 71 99 67 93 20 66 10 84 42 18 24 56 55]
[np.int32(23), np.int32(71), np.int32(67)]
