In [2]:
import numpy as np

In [3]:
myarr = np.array([[3,6,9,12,2]], np.int64)

In [4]:
myarr[0,2]

np.int64(9)

#### Conversion from other python structures

In [5]:
my2darray = np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])

In [6]:
my2darray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
my2darray.dtype

dtype('int64')

In [8]:
my2darray.shape

(4, 3)

In [9]:
my2darray.size

12

In [10]:
np.array({3,5,7,9})

array({9, 3, 5, 7}, dtype=object)

#### Intrinsic numpy array creation objects

In [11]:
zerosarr = np.zeros((3,4), np.int8)

In [12]:
zerosarr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [13]:
zerosarr.shape

(3, 4)

In [14]:
zerosarr.size

12

In [15]:
zerosarr.dtype

dtype('int8')

In [16]:
range_ = np.arange(10,15,2) # range

In [17]:
range_

array([10, 12, 14])

In [18]:
lspace = np.linspace(1,24,7) #Give 7 elemnets b/w 1-24 who has equally space

In [19]:
lspace

array([ 1.        ,  4.83333333,  8.66666667, 12.5       , 16.33333333,
       20.16666667, 24.        ])

In [20]:
emp = np.empty((2,3)) # give empty array and assigned random value in the array

In [21]:
emp

array([[-1.45055918e-311, -1.85531945e-213,  1.45057253e-311],
       [ 1.45057253e-311,  1.33397724e-322,  0.00000000e+000]])

In [22]:
emp_like = np.empty_like(lspace) # copy 'lspace' size and element in the emp_like array

In [23]:
emp_like

array([ 1.        ,  4.83333333,  8.66666667, 12.5       , 16.33333333,
       20.16666667, 24.        ])

In [24]:
iden = np.identity(4) # Give identity matrix of 4x4

In [25]:
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
arr = np.arange(30)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
arr.reshape(6,5) # reshape the given array according to arguments *but it will not change 'arr'*

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
arr = arr.reshape(6,5) # reshape the given array according to arguments *now it will change 'arr'*

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [31]:
arr = arr.ravel() # convert 'arr' in 1D

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
arr.shape

(30,)

In [34]:
x = np.array([[1,2,3],[4,8,5],[2,6,9]],np.int8)

In [35]:
x

array([[1, 2, 3],
       [4, 8, 5],
       [2, 6, 9]], dtype=int8)

In [36]:
x.sum(axis=1) #sum of all column in each row

array([ 6, 17, 17])

In [37]:
x.sum(axis=0) #sum of all row in each col

array([ 7, 16, 17])

In [38]:
x.T #Transpose: interchanging its rows and columns

array([[1, 4, 2],
       [2, 8, 6],
       [3, 5, 9]], dtype=int8)

In [39]:
for item in x.flat:
    print(item)

1
2
3
4
8
5
2
6
9


In [40]:
x.ndim

2

In [41]:
x.nbytes

9

In [42]:
x.size

9

In [43]:
one = np.array([1,3,5,0,888])

In [44]:
one.argmax() # Tells the index of maximum element

np.int64(4)

In [45]:
one.argmin() # Tells the index of minimum element

np.int64(3)

In [46]:
one.argsort() #sort using indices. smallest element at 3rd place, and then second samllest at 0th place and so on. 

array([3, 0, 1, 2, 4])

In [47]:
x

array([[1, 2, 3],
       [4, 8, 5],
       [2, 6, 9]], dtype=int8)

In [48]:
x.argmin() # First convert 2D to 1D (first row then second, then third in straight line). Smallest element at index=0.

np.int64(0)

In [49]:
x.argmax() # First convert 2D to 1D. Smallest element at index=8.

np.int64(8)

In [50]:
x.argmin(axis=0) # check in each column

array([0, 0, 0])

In [51]:
x.argmin(axis=1) # check in each column

array([0, 0, 0])

In [52]:
x.argmax(axis=0) # check in each column

array([1, 1, 2])

In [53]:
x.argmax(axis=1) # check in each column

array([2, 1, 2])

In [54]:
x.reshape(1,9)

array([[1, 2, 3, 4, 8, 5, 2, 6, 9]], dtype=int8)

In [55]:
arr1 = np.array([[1,4,7],[7,3,8]])

In [56]:
arr2 = np.array([[2,4,6],[1,7,9]])

In [57]:
arr1 + arr2

array([[ 3,  8, 13],
       [ 8, 10, 17]])

In [58]:
arr1

array([[1, 4, 7],
       [7, 3, 8]])

In [59]:
arr1*arr2

array([[ 2, 16, 42],
       [ 7, 21, 72]])

In [60]:
np.sqrt(arr1)

array([[1.        , 2.        , 2.64575131],
       [2.64575131, 1.73205081, 2.82842712]])

In [61]:
arr1.sum() # Sum of all elements in arr

np.int64(30)

In [62]:
arr1.max() # Maximum num in arr

np.int64(8)

In [63]:
arr1.min() # Minimum num in arr

np.int64(1)

In [64]:
arr1

array([[1, 4, 7],
       [7, 3, 8]])

In [65]:
np.where(arr1>5) # first array shows rows and second array shows columns

(array([0, 1, 1]), array([2, 0, 2]))

In [66]:
arr3 = np.array([[3,7,0],[2,9,6],[1,6,9]])

In [67]:
arr3

array([[3, 7, 0],
       [2, 9, 6],
       [1, 6, 9]])

In [68]:
np.where(arr3>5)  # first array shows rows and second array shows columns

(array([0, 1, 1, 2, 2]), array([1, 1, 2, 1, 2]))

In [69]:
np.count_nonzero(arr3)

8

In [70]:
np.nonzero(arr3) # tells where element is non zero. first array shows rows and second array shows columns

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 0, 1, 2, 0, 1, 2]))

In [73]:
empty0 = np.empty((2,5))

In [74]:
empty0

array([[nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [77]:
zeros0 = np.zeros((3,4), np.int8)

In [78]:
zeros0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [79]:
ones0 = np.ones((3,2))

In [80]:
ones0

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
array0 = np.array((3,2))

In [84]:
array0

array([3, 2])

In [85]:
marks = np.array([76,78,81,66,85])